import { readFileSync } from 'node:fs';

const REQUIRED_PROJECT_FIELDS = [
  'projectId', 'category', 'name', 'localPath', 'managementType', 'status',
  'priority', 'owner', 'nextAction', 'dueDate', 'repositoryUrl', 'memo',
  'lastConfirmedAt',
];

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

export function readSeed(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function validateSeed(seed) {
  assert(seed && typeof seed === 'object', 'seedはJSONオブジェクトである必要があります');
  assert(seed.schemaVersion === 1, 'schemaVersionは1である必要があります');
  assert(/^\d{4}-\d{2}-\d{2}$/.test(seed.generatedAt), 'generatedAtはyyyy-mm-dd形式です');
  assert(typeof seed.source === 'string' && seed.source.length > 0, 'sourceは必須です');
  assert(Array.isArray(seed.projects) && seed.projects.length > 0, 'projectsは1件以上必要です');

  const ids = new Set();
  const paths = new Set();
  for (const project of seed.projects) {
    for (const field of REQUIRED_PROJECT_FIELDS) {
      assert(Object.hasOwn(project, field), `${project.projectId ?? '(unknown)'}: ${field}がありません`);
    }
    assert(/^PRJ-\d{3,}$/.test(project.projectId), `Project IDが不正です: ${project.projectId}`);
    assert(!ids.has(project.projectId), `Project IDが重複しています: ${project.projectId}`);
    if (project.localPath) assert(!paths.has(project.localPath), `ローカルパスが重複しています: ${project.localPath}`);
    assert(project.status === '棚卸し待ち' || project.status.length > 0, `${project.projectId}: 状態がありません`);
    ids.add(project.projectId);
    if (project.localPath) paths.add(project.localPath);
  }
  return seed;
}

export function renderAppsScript(seed) {
  validateSeed(seed);
  const metadata = {
    schemaVersion: seed.schemaVersion,
    generatedAt: seed.generatedAt,
    source: seed.source,
    projectCount: seed.projects.length,
  };
  return [
    '// Generated by scripts/build.mjs. Do not edit.',
    `const PROJECT_SEED_META = Object.freeze(${JSON.stringify(metadata, null, 2)});`,
    `const PROJECT_SEED = Object.freeze(${JSON.stringify(seed.projects, null, 2)});`,
    '',
  ].join('\n');
}
