import { readFileSync } from 'node:fs';

const REQUIRED_PROJECT_FIELDS = [
  'projectId', 'category', 'name', 'localPath', 'managementType', 'status',
  'priority', 'owner', 'nextAction', 'dueDate', 'repositoryUrl', 'memo',
  'lastConfirmedAt',
];

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

export function readSeed(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

export function validateSeed(seed) {
  assert(seed && typeof seed === 'object', 'seedはJSONオブジェクトである必要があります');
  assert(seed.schemaVersion === 1, 'schemaVersionは1である必要があります');
  assert(/^\d{4}-\d{2}-\d{2}$/.test(seed.generatedAt), 'generatedAtはyyyy-mm-dd形式です');
  assert(typeof seed.source === 'string' && seed.source.length > 0, 'sourceは必須です');
  assert(Array.isArray(seed.projects) && seed.projects.length > 0, 'projectsは1件以上必要です');

  const ids = new Set();
  const paths = new Set();
  for (const project of seed.projects) {
    for (const field of REQUIRED_PROJECT_FIELDS) {
      assert(Object.hasOwn(project, field), `${project.projectId ?? '(unknown)'}: ${field}がありません`);
    }
    assert(/^PRJ-\d{3,}$/.test(project.projectId), `Project IDが不正です: ${project.projectId}`);
    assert(!ids.has(project.projectId), `Project IDが重複しています: ${project.projectId}`);
    if (project.localPath) assert(!paths.has(project.localPath), `ローカルパスが重複しています: ${project.localPath}`);
    assert(project.status === '棚卸し待ち' || project.status.length > 0, `${project.projectId}: 状態がありません`);
    ids.add(project.projectId);
    if (project.localPath) paths.add(project.localPath);
  }
  return seed;
}

export function renderAppsScript(seed) {
  validateSeed(seed);
  const metadata = {
    schemaVersion: seed.schemaVersion,
    generatedAt: seed.generatedAt,
    source: seed.source,
    projectCount: seed.projects.length,
  };
  return [
    '// Generated by scripts/build.mjs. Do not edit.',
    `const PROJECT_SEED_META = Object.freeze(${JSON.stringify(metadata, null, 2)});`,
    `const PROJECT_SEED = Object.freeze(${JSON.stringify(seed.projects, null, 2)});`,
    '',
  ].join('\n');
}

export function validateSingleSeed(seed) {
  assert(seed && typeof seed === 'object', 'single seedはJSONオブジェクトである必要があります');
  assert(seed.schemaVersion === 1, 'schemaVersionは1である必要があります');
  assert(/^\d{4}-\d{2}-\d{2}$/.test(seed.generatedAt), 'generatedAtはyyyy-mm-dd形式です');
  assert(typeof seed.source === 'string' && seed.source.length > 0, 'sourceは必須です');
  assert(seed.project && typeof seed.project === 'object', 'projectは必須です');
  ['id', 'name', 'purpose', 'sponsor', 'manager', 'status'].forEach(function(field) {
    assert(typeof seed.project[field] === 'string', `project.${field}は文字列である必要があります`);
  });
  ['workItems', 'raid', 'stakeholders', 'changesDecisions'].forEach(function(field) {
    assert(Array.isArray(seed[field]), `${field}は配列である必要があります`);
  });
  const datePattern = /^\d{4}-\d{2}-\d{2}$/;
  ['startDate', 'targetDate', 'lastReview', 'nextReview'].forEach(function(field) {
    if (seed.project[field]) assert(datePattern.test(seed.project[field]), `project.${field}はyyyy-mm-dd形式です`);
  });
  const ids = new Set();
  [
    ['workItems', ['start', 'due', 'baselineStart', 'baselineEnd', 'actualStart', 'actualEnd']],
    ['raid', ['registered', 'due']],
    ['stakeholders', ['last', 'next']],
    ['changesDecisions', ['registered', 'target', 'decisionDate']],
  ].forEach(function(spec) {
    seed[spec[0]].forEach(function(item) {
      assert(typeof item.id === 'string' && item.id.length > 0, `${spec[0]}のidは必須です`);
      assert(!ids.has(item.id), `Single profile内でIDが重複しています: ${item.id}`);
      ids.add(item.id);
      spec[1].forEach(function(field) {
        if (item[field]) assert(datePattern.test(item[field]), `${item.id}.${field}はyyyy-mm-dd形式です`);
      });
    });
  });
  const workItemIds = new Set(seed.workItems.map(function(item) { return item.id; }));
  seed.workItems.forEach(function(item) {
    if (item.parentId) assert(workItemIds.has(item.parentId), `${item.id}: 親IDが存在しません: ${item.parentId}`);
    if (item.level !== undefined) assert(Number.isInteger(item.level) && item.level >= 1 && item.level <= 10, `${item.id}: levelは1から10の整数です`);
    if (item.progress !== undefined) assert(item.progress >= 0 && item.progress <= 1, `${item.id}: progressは0から1です`);
  });
  return seed;
}

export function renderSingleAppsScript(seed) {
  validateSingleSeed(seed);
  return [
    '// Generated by scripts/build.mjs. Do not edit.',
    `const SINGLE_PROJECT_SEED_META = Object.freeze(${JSON.stringify({ schemaVersion: seed.schemaVersion, generatedAt: seed.generatedAt, source: seed.source }, null, 2)});`,
    `const SINGLE_PROJECT_SEED = Object.freeze(${JSON.stringify(seed, null, 2)});`,
    '',
  ].join('\n');
}
