function verifySingleProjectWorkbook_(ss) {
  SpreadsheetApp.flush();
  const expected = SINGLE_SHEET_ORDER;
  const names = ss.getSheets().map(function(sheet) { return sheet.getName(); });
  const missingSheets = expected.filter(function(name) { return names.indexOf(name) === -1; });
  const errors = [];
  ss.getSheets().forEach(function(sheet) { sheet.getDataRange().getDisplayValues().forEach(function(row, rowIndex) { row.forEach(function(value, columnIndex) { if (/^#(?:REF!|DIV\/0!|VALUE!|NAME\?|N\/A|NUM!|ERROR!)/.test(value)) errors.push(sheet.getName() + '!' + sheet.getRange(rowIndex + 1, columnIndex + 1).getA1Notation()); }); }); });
  const dashboard = ss.getSheetByName(SINGLE_SHEET_NAMES.dashboard); const summary = ss.getSheetByName(SINGLE_SHEET_NAMES.summarySchedule); const work = ss.getSheetByName(SINGLE_SHEET_NAMES.workItems); const gantt = ss.getSheetByName(SINGLE_SHEET_NAMES.gantt); const raid = ss.getSheetByName(SINGLE_SHEET_NAMES.raid); const stakeholders = ss.getSheetByName(SINGLE_SHEET_NAMES.stakeholders); const decision = ss.getSheetByName(SINGLE_SHEET_NAMES.decisions);
  const report = { sheets: names, missingSheets: missingSheets, formulaErrors: errors, validations: {}, filters: {}, frozenHeaders: {}, conditionalFormats: {}, dashboardFormulas: [], summaryFormulas: [], summaryLayout: {}, ganttFormulas: [] };
  if (missingSheets.length) { report.passed = false; return report; }
  report.validations = { wbsLevel: Boolean(work.getRange('C2').getDataValidation()), wbsType: Boolean(work.getRange('D2').getDataValidation()), wbsStatus: Boolean(work.getRange('F2').getDataValidation()), summaryUnit: Boolean(summary.getRange('F3').getDataValidation()), summaryPeriods: Boolean(summary.getRange('H3').getDataValidation()), ganttUnit: Boolean(gantt.getRange('E2').getDataValidation()), ganttPeriods: Boolean(gantt.getRange('H2').getDataValidation()), raidType: Boolean(raid.getRange('B2').getDataValidation()), decisionType: Boolean(decision.getRange('B2').getDataValidation()), decisionStatus: Boolean(decision.getRange('H2').getDataValidation()) };
  report.filters = { wbs: Boolean(work.getFilter()), raid: Boolean(raid.getFilter()), stakeholders: Boolean(stakeholders.getFilter()), decisions: Boolean(decision.getFilter()) };
  expected.forEach(function(name) { const sheet = ss.getSheetByName(name); report.frozenHeaders[name] = name === SINGLE_SHEET_NAMES.dashboard ? sheet.getFrozenRows() >= 2 : sheet.getFrozenRows() >= 1; });
  [SINGLE_SHEET_NAMES.dashboard, SINGLE_SHEET_NAMES.summarySchedule, SINGLE_SHEET_NAMES.workItems, SINGLE_SHEET_NAMES.gantt, SINGLE_SHEET_NAMES.raid, SINGLE_SHEET_NAMES.decisions].forEach(function(name) { report.conditionalFormats[name] = ss.getSheetByName(name).getConditionalFormatRules().length > 0; });
  report.dashboardFormulas = dashboard.getRange('A5:H5').getFormulas()[0];
  report.summaryFormulas = [summary.getRange('A6').getFormula(), summary.getRange('H5').getFormula(), summary.getRange('Y5').getFormula(), summary.getRange('H6').getFormula(), summary.getRange('Y6').getFormula()];
  const summaryMerges = summary.getDataRange().getMergedRanges().map(function(range) { return range.getA1Notation(); });
  const hasEligibleSummaryItems = work.getRange('A2:D' + SINGLE_MAX_ROWS).getDisplayValues().some(function(row) { return row[0] && (row[2] === '1' || row[3] === 'マイルストーン'); });
  report.summaryLayout = { frozenRows: summary.getFrozenRows() === 5, frozenColumns: summary.getFrozenColumns() === 0, titleMerge: summaryMerges.indexOf('A1:Y1') >= 0, subtitleMerge: summaryMerges.indexOf('A2:Y2') >= 0, reviewLabelMerge: summaryMerges.indexOf('I3:K3') >= 0, reviewDateMerge: summaryMerges.indexOf('L3:N3') >= 0, conditionalRuleCount: summary.getConditionalFormatRules().length === 6, extractedData: !hasEligibleSummaryItems || summary.getRange('A6').getDisplayValue().length > 0 };
  report.ganttFormulas = [gantt.getRange('A5').getFormula(), gantt.getRange('L4').getFormula(), gantt.getRange('L5').getFormula()];
  report.passed = report.formulaErrors.length === 0 && report.dashboardFormulas.every(function(formula) { return formula.length > 0; }) && report.summaryFormulas.every(function(formula) { return formula.length > 0; }) && report.ganttFormulas.every(function(formula) { return formula.length > 0; }) && Object.keys(report.validations).every(function(key) { return report.validations[key]; }) && Object.keys(report.filters).every(function(key) { return report.filters[key]; }) && Object.keys(report.frozenHeaders).every(function(key) { return report.frozenHeaders[key]; }) && Object.keys(report.conditionalFormats).every(function(key) { return report.conditionalFormats[key]; }) && Object.keys(report.summaryLayout).every(function(key) { return report.summaryLayout[key]; });
  return report;
}
